# Generated by Django 4.1.1 on 2022-09-21 12:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hiringsupervisors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('positiontitle', models.CharField(max_length=200)),
                ('wagerange', models.FloatField(max_length=200)),
                ('essentialfunctions', models.TextField()),
                ('skillsrequired', models.TextField()),
                ('education_knowledgerequired', models.TextField()),
                ('experiencerequired', models.IntegerField()),
                ('physicalrequirements', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('dateofrequisition', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('hiringsupervisors', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hiringsupervisors.hiringsupervisors')),
            ],
        ),
    ]
