# Generated by Django 4.1.2 on 2022-10-15 19:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('lowwage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('highwage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('essentialfunctions', models.TextField()),
                ('skillsrequired', models.TextField()),
                ('education_knowledgerequired', models.TextField()),
                ('experiencerequired', models.IntegerField()),
                ('physicalrequirements', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('dateofrequisition', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField()),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.manager')),
            ],
        ),
    ]
